// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8WqrHZhR2KvD_kYHbPrL6byJ4iaj_So',
    appId: '1:508529006367:web:52d3735905a01cdd43422a',
    messagingSenderId: '508529006367',
    projectId: 'fitgroup-mobile',
    authDomain: 'fitgroup-mobile.firebaseapp.com',
    storageBucket: 'fitgroup-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKr7AWHstLiIB-yfMCTzyzK5J5NvUK1Q',
    appId: '1:508529006367:android:e0c8a5ccb5d053fe43422a',
    messagingSenderId: '508529006367',
    projectId: 'fitgroup-mobile',
    storageBucket: 'fitgroup-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxDTGpL6siiz9L2ac1bw-XlXcMB0_dg0',
    appId: '1:508529006367:ios:fe00bf2a7d0d191a43422a',
    messagingSenderId: '508529006367',
    projectId: 'fitgroup-mobile',
    storageBucket: 'fitgroup-mobile.firebasestorage.app',
    iosBundleId: 'com.example.fitgroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxDTGpL6siiz9L2ac1bw-XlXcMB0_dg0',
    appId: '1:508529006367:ios:fe00bf2a7d0d191a43422a',
    messagingSenderId: '508529006367',
    projectId: 'fitgroup-mobile',
    storageBucket: 'fitgroup-mobile.firebasestorage.app',
    iosBundleId: 'com.example.fitgroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8WqrHZhR2KvD_kYHbPrL6byJ4iaj_So',
    appId: '1:508529006367:web:a8aeb8ff5684adaf43422a',
    messagingSenderId: '508529006367',
    projectId: 'fitgroup-mobile',
    authDomain: 'fitgroup-mobile.firebaseapp.com',
    storageBucket: 'fitgroup-mobile.firebasestorage.app',
  );
}
